### PR TITLE
Added fire critical request button to test app

### PR DESCRIPTION
**Pull request by sanecito**

### CODE REVIEW

**Comment by sean97140** [comment]
@askore do you want to fix the conflict, or should I?

**Comment by askore** [comment]
@sean97140 I'm on my desktop so I don't have the workflow set up, could you please resolve it?

**Comment by askore** [comment]
@sean97140 @sanecito This doesn't look like it got merged; did the functionality get added in a different pull request or something?

**Comment by ryan52** [comment]
@askore, this was included as part of:
fix scott's merge conflict, add charging status indicator (#57)

On Sun, Jan 25, 2015 at 09:01:52AM -0800, Brianna Buckner wrote:
> @sean97140 @sanecito This doesn't look like it got merged; did the
> functionality get added in a different pull request or something?
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

--

**Comment by ryan52** [comment]
if @sean97140 had used "git merge" to resolve this conflict (and therefor also include Scott's commit in the history of our branch), then it would not be showing "Closed with unmerged commits" right now.

**Comment by sean97140** [comment]
either I will make sure to reference it on the request I close, or someone
can teach me how to resolve merge conflicts the way you are discussing.

**Pull request closed without merging**
