### PR TITLE
record critical vs non critical, success vs failure and status code

### PR DESCRIPTION
**Pull request by sean97140**
Finished my 2 tasks and found a bug with previous task I did so I fixed it (33-37).

### CODE REVIEW

**Comment by sean97140** [comment]
I don't see travis on this... Anyone know why?

**Comment by gaobin1019** [comment]
describe ('404 request should have a timestamp stored too', function(){
it('makes an 404 request', function(done){
AL.ajax('wfeiojwfe<<', null,function(result, status, xhr){
expect(result).toBe('NOT FOUND');
expect(status).toBe(404);
AL.getLatestAccessTimeStamp(function(data){
expect(data).not.toBe(null);
done();
});
});
});
});


I wrote this test for recording an unsuccessful request's time stamp.

It failures because  getLatestAccessTimeStamp pops off all the unsuccessful
values.

Are we assuming getLatestAccessTimeStamp only record the successful
requests' time stamp which means I need to test getHistory function instead?

Thanks,

Bin

**Comment by sean97140** [comment]
Oh, I did that because the method you are calling is designed to get the
successful attempts. A test is already written that confirms this
behavior. If you want to change this, we need to make a new method called
getLastAccessAttemptTimestamp and rename the other one to
getLastSuccesfulAcessTimestamp. or we can make an optional Boolean flag on
the current method called "getUnsuccessfulRequests" (which is probably the
simple way to go. I can whip this up in 10 minutes if you want me to, or
you are more than welcome to do it if you wish.

Sean

**Comment by sean97140** [comment]
Bin, try this

```
describe ('404 request should have a timestamp stored too', function(){
    it('makes an 404 request', function(done){
        AL.ajax('wfeiojwfe<<', null,function(result, status, xhr){
            expect(result).toBe('NOT FOUND');
            expect(status).toBe(404);
            AL.getLatestAccessTimeStamp(function(data){
                expect(data).not.toBe(null);
                done();
            }, true);
        });
    });
});
```

**Comment by gaobin1019** [comment]
if (first['status'] === 'successful') {
callback(first['end']);
} else {
while (first['status'] === 'failure'){
first = value.pop();
}
callback(first['end']);
}

Sorry, I take it back what I said last night... The original version is
above, it did calls the callback with failure value(But may not be the
latest one)

I must did something wrong on my test.

**Comment by gaobin1019** [comment]
You are right sean, I didn't wake up yet .... didn't see the pop at top of
the function.

Anyway, this fixed my error.

I made a pull request.

Thanks for your help sean,

Bin

**Pull request merged**
