### PR TITLE
Cenglish/automation

### PR DESCRIPTION
**Pull request by razanur37**
Added Nightwatch.js support for automated testing of the application. Includes updated .travis.yml file to support Nightwatch testing during Travis builds.

### CODE REVIEW

**Comment by TheBosZ** [comment]
This is by far the best commit history I have ever seen.

**Comment by sean97140** [comment]
Now that Nathan mentions it, wow

**Comment by huynt553** [comment]
Hahahaha that's just great

**Comment by askore** [comment]
That IS impressive...

**Pull request merged**
