### PR TITLE
Added quantity field for non-critical requests, ability to auto-add n-cr's with critical request button, and adjusted UI

### PR DESCRIPTION
**Pull request by sanecito**
UI adjusted to be grouped by function (non-critical, critical,
historical) to make the giant set of toggles, fields, and buttons more
readable and less intimidating.

### CODE REVIEW

**Comment by sean97140** [comment]
you seem to be getting lucky with travis, lol.

**Comment by sanecito** [comment]
Not sure why Travis is failing the way it is; this pull request only touches the index.html and javascript for the demo app...shouldn't affect Jasmine/Karma.

**Comment by sean97140** [comment]
it breaks randomly, you just got the winning lottery ticket this time.

**Comment by sean97140** [comment]
my build is failing too. i think one of the sites we use is down.

**Comment by sanecito** [comment]
Yep, developer.mozilla.org/search.json is down:
http://doj.me/?url=developer.mozilla.org%2Fsearch.json%3Fq%3Dcats

**Comment by sean97140** [comment]
maybe our testing or app brought it down. we are sending hundreds of
requests to it...

**Comment by TheBosZ** [comment]
We should replace all the URLs with the Heroku one.

**Comment by ryan52** [comment]
We should use heroku for any testing we are doing involving hundreds.

**Comment by askore** [comment]
@TheBosZ @ryan52 We could merge this now, or replace the URLs with Heroku in a different PR and then run the tests again for this branch. Preference?

**Comment by TheBosZ** [comment]
Eh. A new PR and then merge master into this branch would probably be best.

Give me a couple minutes to make a PR.

**Comment by TheBosZ** [comment]
Okay, with my branch: kerr/change-all-testing-urls all tests pass.

**Comment by askore** [comment]
Cool, all is well again, will merge.

**Comment by TheBosZ** [comment]
There's a merge conflict because I changed the default URL in the example app. Should be easy to resolve.

**Pull request closed without merging**
