### PR TITLE
Added non-critical requests firing when any request is fired

### PR DESCRIPTION
**Pull request by sanecito**

### CODE REVIEW

**Comment by TheBosZ** [comment]
This doesn't match the desired behavior: only a successful request should fire the event.

**Comment by sanecito** [comment]
What constitutes 'success'? A readyState of 4?

**Comment by TheBosZ** [comment]
We're not checking readyStates. "onload" constitutes success. The event should be emitted from within the "successCallback" function.

**Comment by TheBosZ** [comment]
In fact, we're already doing this on line 27

**Comment by sanecito** [comment]
So "Fire pending non-critical requests when a critical request fires" is already happening then as I understand it. Correct?

**Comment by TheBosZ** [comment]
Yes

**Comment by sanecito** [comment]
Alright, I'll double check at the meeting that's the meaning Dietrich/everybody agrees upon. I was under the impression "Fire pending non-critical requests when a critical request fires" was for when send() was called, but system resources wise, it only makes sense to call the non-critical queue when there's been success as per current implementation.

**Comment by sanecito** [comment]
Yep, it looks like nothing needs to be changed for this feature. Per Dietrich's comments on etherpad: "wrap xmlhttp request, which sends the custom event when the request is completed". Deleting the branch. Thanks for catching that!

**Pull request closed without merging**
