### PR TITLE
Non-critical request button and url txt field added to test app

### PR DESCRIPTION
**Pull request by sean97140**
The network-ready button is not working (assuming it was never tested), maybe the simulator i am using. @TheBosZ , can you look at this?

### CODE REVIEW

**Comment by TheBosZ** [comment]
It appears to be working just fine for me. I changed the callback for the non-crit requests to echo to the console and I get as many messages as I expected.

What behavior are you seeing?

**Comment by sean97140** [comment]
The counter does not go to zero when I click the network ready button

**Comment by TheBosZ** [comment]
Hmm... it does for me. Did you do a grunt build?

If you have the callbacks log to the console when they complete, do you see the messages in the console?

**Comment by sean97140** [comment]
forgot about the grunt build, it was an outdated firefoxos.js file.

**Comment by TheBosZ** [comment]
Sweet! I like problems that have a simple solution!

**Pull request merged**
