### PR TITLE
Create "Hello World" b2g app for testing

### PR DESCRIPTION
**Pull request by askore**
The basic outline of a firefox OS app to be filled out with some buttons for testing the battery harness. @ryan52 had some concerns about whether the symlink should be pointing at lib/firefoxos.js or dist/firefoxos.js, but since it's just a symlink that can be changed later if needed. This runs with no errors in the web IDE simulator.

### CODE REVIEW

**Comment by TheBosZ** [comment]
It should definitely be the dist version as it packages up localforage as well as our library.

**Comment by askore** [comment]
That makes sense, although right now nothing in dist is being tracked in git. Should I just add it?

**Comment by ryan52** [comment]
Since the dist file is built it should not be checked into source control. Can we symlink to it without checking in?

**Comment by askore** [comment]
Sure, it's a symbolic link, we can do anything we want. However, since the firefox os app doesn't explicitly require running grunt build, it's possible that it could be pulled down and run without building first.

**Comment by ryan52** [comment]
@askore, we will need to update the README documenting that "grunt build" must be ran first.

**Pull request merged**
