### PR TITLE
Fix some potential bugs with handling of the charging status

### PR DESCRIPTION
**Pull request by ryan52**
Hey @TheBosZ , do these changes make sense?

I was getting some errors running battest in Chrome (silly, I know) and looked through the code quickly.

### CODE REVIEW

**Comment by TheBosZ** [comment]
I've fixed the now is good manager code in one of my branches that's waiting to be merged.

For app.js:65, don't check the property that way. If .getbattery doesn't exist, you'll get an error. Instead use:
typeof navigator.battery === 'function'

**Comment by ryan52** [comment]
@TheBosZ , alright, I reverted the change to the now is good manager, and made that improvement.

**Comment by ryan52** [comment]
@TheBosZ, should this be merged now? If so, @askore or @sean97140 can you please merge it in?

**Comment by TheBosZ** [comment]
Yes, it can be merged.

**Pull request merged**
